name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: cscope_maps
          pandoc: "README.md"
          version: "Neovim >= v0.10.0"
          treesitter: true
          demojify: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate"
          branch: ${{ github.head_ref }}
